//
// Created by Elias Magdaleno on 12/9/23.
//

#ifndef INC_340DOUBLYLINKEDLIST_ELEVATORTEST_H
#define INC_340DOUBLYLINKEDLIST_ELEVATORTEST_H

void elevatorTest();

#endif //INC_340DOUBLYLINKEDLIST_ELEVATORTEST_H


